### PR TITLE
Footer edit

### PR DESCRIPTION
**Pull request by 05hiteshbansal**
bugs Fixed

### CODE REVIEW

**Comment by 05hiteshbansal** [comment]
@devbytemehedi  Please Merge it

**Comment by devbytemehedi** [comment]
@05hiteshbansal wait let me check

**Comment by 05hiteshbansal** [comment]
can you send me a screenshot of problem @devbytemehedi

**Comment by 05hiteshbansal** [comment]
I tested the website before

**Comment by devbytemehedi** [comment]
Screenshot_2023-08-29-23-53-04-22_4d38fce200f96aeac5e860e739312e76

**Comment by devbytemehedi** [comment]
@05hiteshbansal change the color of the footer text based on the light and dark mode of  the website and
 > after completeing and testing create the pull request in that same branch again.

**Pull request merged**
